In [1]:
import numpy as np 

In [4]:
arr = np.array([1,2,3,4,5,5]) #1d array
arr2d = np.array([[1,2,3,4],[2,3,4,5]]) #2d array
print(arr)
print(arr2d)

[1 2 3 4 5 5]
[[1 2 3 4]
 [2 3 4 5]]


In [5]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [6]:
zero = np.zeros((2,3))#fill row and col with zero
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
one = np.ones((5,3)) #fill with 1
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
fu = np.full((3,4), 6) #filling a specific value
fu

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [13]:
ey = np.eye(5) #prints value in diagonal form
ey

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
lspace = np.linspace(0,2, 5) #(starting, ending, no. of elements) it gives element which is evenly spaced
lspace

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
import random

In [23]:
arr = np.random.random((2,3)) #random elements between 0-1
arr

array([[0.21544688, 0.71206714, 0.54755748],
       [0.10433947, 0.89219397, 0.22994368]])

In [26]:
arr = np.random.randint(10, size=(2,3)) #random value between 0-10
arr

array([[3, 9, 6],
       [6, 8, 3]])

## Some properties

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [29]:
arr.shape

(2, 4)

In [31]:
arr.ndim #gives dimensions

2

In [32]:
arr.dtype

dtype('int64')

In [35]:
arr = np.array([[1,2,3,4],[5,6,7,8]], dtype='float32') #explicitly dtype conversion
arr.dtype


dtype('float32')

In [36]:
arr = np.array([[1,2,3,4],[5,6,7,8]])


In [40]:
 a = arr.astype('float64')

In [41]:
a.dtype

dtype('float64')

# reshpe

In [42]:
arr.shape

(2, 4)

In [49]:
new = arr.reshape((4,2))

In [50]:
new.shape

(4, 2)

In [51]:
a=new.flatten()
a

array([1, 2, 3, 4, 5, 6, 7, 8])