In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 20)

In [4]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [11]:
mask = arr >25
arr[mask]

array([30, 40, 50])

## Slicing returns a view, not a copy! Changes affect the original array.

In [12]:
a = arr[:3]

In [13]:
a

array([10, 20, 30])

In [14]:
a[0] = 1000
a

array([1000,   20,   30])

In [16]:
arr # now the original array also changed 

array([1000,   20,   30,   40,   50])

In [19]:
b = arr[:4].copy() #copy function used, so it not change the original array

In [20]:
b

array([1000,   20,   30,   40])

In [21]:
b[0] = 200

In [22]:
b

array([200,  20,  30,  40])

In [23]:
arr

array([1000,   20,   30,   40,   50])

In [44]:
# we can also reshape an array if we don't know about its length and calculation of the rows and cols
# but we need to defines row or col in a way so it can create a matrices
# not like that (5,3) if we have 20 elements it is not possible to create (5,3) matrices
arr = np.arange(20)
reshape2dcol = arr.reshape(-1, 5) #here -1 is unknown we only write here how many cols we needed and it automatically defines the rows
print(f"Reshaped 2d array column wise : {reshape2dcol}")

reshape2drow = arr.reshape(5,-1)#here we defines the row and it automatically takes the no. of cols 
print(f"Reshaped 2d array row wise : {reshape2drow}")

reshaped3d = arr.reshape(1,5,-1)
print(f"3d array : {reshaped3d}")


# conerting 2d,3d array in flatten in another way:
arr2 = reshaped3d.reshape(-1)#put -1 it convert in into flatten array
print(f"flatten array : {arr2}")

Reshaped 2d array column wise : [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Reshaped 2d array row wise : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
3d array : [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]]
flatten array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#

In [26]:
import random

In [27]:
# Create a 3×3 array filled with random numbers and print its shape.
arr = np.random.randint(10, size=(3,3))
arr

array([[5, 7, 9],
       [7, 6, 5],
       [4, 3, 9]])

In [32]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr = np.array([1.1, 2.2, 3.3,4,4])
arr1 = arr.astype('int64')
arr = np.array([1.1, 2.2, 3.3,4,4], dtype='int64')
print(arr1.dtype)
print(arr.dtype)

int64
int64


In [35]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr = np.array([1,2,3,4,5,6])
idx = [1,3,5]
print(arr[idx])
mask = arr % 2 == 0
arr[mask]

[2 4 6]


array([2, 4, 6])

In [38]:
# Reshape a 1D array of size 9 into a 3×3 matrix.
arr = np.arange(1,10)
arr = arr.reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
# Use boolean masking to filter numbers greater than 50 in an array. 
arr = np.random.randint(100, size=(20,5))
mask = arr>50
arr[mask]

array([91, 75, 59, 70, 77, 98, 80, 78, 81, 70, 54, 90, 73, 59, 78, 88, 73,
       80, 98, 58, 84, 68, 69, 84, 72, 84, 69, 82, 63, 93, 72, 97, 78, 53,
       92, 76, 56, 53, 72, 87, 65, 53, 73, 93, 52, 79, 90, 75, 82, 69, 72,
       85, 91, 87, 71, 74, 69, 89])