In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,2,5,7,4])
arr*2

array([ 2,  6,  4, 10, 14,  8])

In [3]:
arr = np.array([[1,2,3,4],
               [5,6,7,8], 
               [9,10,1,12]])

In [8]:
mean = arr.mean()
stand = arr.std()


In [9]:
normalize_data = (arr-mean)/stand
normalize_data

array([[-1.34404301, -1.05603379, -0.76802458, -0.48001536],
       [-0.19200614,  0.09600307,  0.38401229,  0.67202151],
       [ 0.96003072,  1.24803994, -1.34404301,  1.82405837]])

In [10]:
arr = np.array([[1,3,2], [5,6,7]])
arr2 = np.array([1,2,3])
arr + arr2

array([[ 2,  5,  5],
       [ 6,  8, 10]])