In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3], [4,5,6]])

In [6]:
print(arr.sum(axis = 0))
print(arr.sum(axis=1))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[5 7 9]
[ 6 15]
[5 7 9]
[ 6 15]


In [7]:
print(arr.min(axis = 0))
print(arr.min(axis=1))
print(np.min(arr, axis=0))
print(np.min(arr, axis=1))

[1 2 3]
[1 4]
[1 2 3]
[1 4]


In [8]:
print(arr.max(axis = 0))
print(arr.max(axis=1))
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))

[4 5 6]
[3 6]
[4 5 6]
[3 6]


In [9]:
print(arr.mean(axis = 0))
print(arr.mean(axis=1))
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[2.5 3.5 4.5]
[2. 5.]
[2.5 3.5 4.5]
[2. 5.]


In [10]:
arr = np.array([1,2,3,4,5])

In [14]:
np.std(arr) #standard deviation
#or
arr.std()

np.float64(1.4142135623730951)

In [15]:
#we can use function via np.functionname(variable) or variable.functionname


In [16]:
np.var(arr)    #variance

np.float64(2.0)

In [19]:
np.argmax(arr) #index of max element

np.int64(4)

In [20]:
arr.argmin() #index of min element

np.int64(0)

In [30]:
arr.prod() #product

np.int64(120)

In [31]:
np.percentile(arr, 50) #this function not follows variable.functionname()

np.float64(3.0)

In [33]:
np.corrcoef(arr) #correlation coefficient
# #this function not follows variable.functionname()

np.float64(1.0)

In [36]:
np.unique(arr) #unique elements

array([1, 2, 3, 4, 5])

In [39]:
np.diff(arr) #nth difference
# 2 - 1 = 1
# 3 - 2 = 1
# 4 - 3 = 1
# 5 - 4 = 1


array([1, 1, 1, 1])

In [41]:
np.cumsum(arr) #cummulative sum
# kind of fibonacci series 
# we have 1,2,3,4,5
#  1, 1+2 = 3, 3+3 =6, 6+4=10....... 

array([ 1,  3,  6, 10, 15])

In [46]:
np.log(arr) #logrithmoc

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [47]:
np.exp(arr) #exponential

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])